[package]
name = "ordhook-cli"
version = "1.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "ordhook"
path = "src/main.rs"

[dependencies]
ordhook = { path = "../ordhook-core" }
num_cpus = "1.16.0"
serde = "1"
serde_json = "1"
serde_derive = "1"
hex = "0.4.3"
reqwest = { version = "0.11", default-features = false, features = ["stream", "json", "rustls-tls"] }
hiro-system-kit = "0.3.1"
clap = { version = "3.2.23", features = ["derive"], optional = true }
clap_generate = { version = "3.0.3", optional = true }
toml = { version = "0.5.6", features = ["preserve_order"], optional = true }
ctrlc = { version = "3.2.2", optional = true }

[features]
default = ["cli"]
cli = ["clap", "clap_generate", "toml", "ctrlc", "hiro-system-kit/log"]
debug = ["hiro-system-kit/debug"]
release = ["hiro-system-kit/release"]
